export const GBP_CATEGORIES: string[] = [
  'Aadhaar center',
  'Abarth dealer',
  'Abbey',
  'Aboriginal and Torres Strait Islander organisation',
  'Aboriginal art gallery',
  'Abortion clinic',
  'Abrasives supplier',
  'Abundant Life church',
  'Acaraje restaurant',
  'Accountant',
  'Accounting firm',
  'Accounting school',
  'Acoustical consultant',
  'Acrobatic diving pool',
  'Acrylic store',
  'Acupuncture clinic',
  'Acupuncture school',
  'Acupuncturist',
  'Acura dealer',
  'Addiction treatment center',
  'Administrative attorney',
  'Adoption agency',
  'Adult day care center',
  'Adult DVD store',
  'Adult education school',
  'Adult entertainment club',
  'Adult entertainment store',
  'Adult foster care service',
  'Adventure sports center',
  'Advertising agency',
  'Aerated drinks supplier',
  'Aerial photographer',
  'Aerial sports center',
  'Aero dance class',
  'Aerobics instructor',
  'Aeroclub',
  'Aeromodel shop',
  'Aeronautical engineer',
  'Aerospace company',
  'Afghan restaurant',
  'African goods store',
  'African restaurant',
  'After school program',
  'Air ambulance service',
  'Air compressor repair service',
  'Air compressor supplier',
  'Air conditioning contractor',
  'Air conditioning repair service',
  'Air conditioning store',
  'Air conditioning system supplier',
  'Air duct cleaning service',
  'Air filter supplier',
  'Air force base',
  'Air taxi',
  'Airbrushing service',
  'Airbrushing supply store',
  'Aircraft dealer',
  'Aircraft maintenance company',
  'Aircraft manufacturer',
  'Aircraft rental service',
  'Aircraft supply store',
  'Airline',
  'Airline ticket agency',
  'Airport',
  'Airport shuttle service',
  'Airsoft supply store',
  'Airstrip',
  'Alcohol manufacturer',
  'Alcoholic beverage wholesaler',
  'Alcoholism treatment program',
  'Alternative fuel station',
  'Alternative medicine practitioner',
  'Alternator supplier',
  'Aluminum frames supplier',
  'Aluminum supplier',
  'Aluminum welder',
  'Ambulance service',
  'American grocery store',
  'American restaurant',
  'Ammunition supplier',
  'Amusement center',
  'Amusement machine supplier',
  'Amusement park',
  'Anesthesiologist',
  'Animal cafe',
  'Animal control service',
  'Animal hospital',
  'Animal protection organization',
  'Animal rescue service',
  'Animal shelter',
  'Animation studio',
  'Anodizing service',
  'Antique furniture restoration service',
  'Antique furniture store',
  'Antique store',
  'Apartment building',
  'Apartment complex',
  'Apartment rental agency',
  'Appliance parts supplier',
  'Appliance rental service',
  'Appliance repair service',
  'Appliance store',
  'Aquaculture farm',
  'Aquarium',
  'Aquarium shop',
  'Aquatic center',
  'Arab restaurant',
  'Arboretum',
  'Arborist service',
  'Archaeological museum',
  'Archery club',
  'Archery range',
  'Archery store',
  'Architect',
  'Architectural designer',
  'Architectural salvage store',
  'Architecture firm',
  'Architecture school',
  'Archive',
  'Arena',
  'Argentinian restaurant',
  'Armenian church',
  'Armenian restaurant',
  'Army & navy surplus shop',
  'Aromatherapy class',
  'Aromatherapy service',
  'Aromatherapy supply store',
  'Art cafe',
  'Art center',
  'Art dealer',
  'Art gallery',
  'Art museum',
  'Art restoration service',
  'Art school',
  'Art studio',
  'Art supply store',
  'Artist',
  'Asbestos testing service',
  'Ashram',
  'Asian fusion restaurant',
  'Asian grocery store',
  'Asian restaurant',
  'Asphalt contractor',
  'Assisted living facility',
  'Aston Martin dealer',
  'Astrologer',
  'Asylum center',
  'Athletic club',
  'Athletic field',
  'Athletic park',
  'Athletic track',
  'ATM',
  'Auction house',
  'Audiologist',
  'Auditor',
  'Auditorium',
  'Australian restaurant',
  'Auto accessories wholesaler',
  'Auto air conditioning service',
  'Auto auction',
  'Auto body parts supplier',
  'Auto body shop',
  'Auto broker',
  'Auto dent removal service',
  'Auto electrical service',
  'Auto glass repair service',
  'Auto glass shop',
  'Auto insurance agency',
  'Auto parts store',
  'Auto repair shop',
  'Auto restoration service',
  'Auto wrecker',
  'Automation company',
  'Açaí shop',
  'Baby clothing store',
  'Baby store',
  'Bakery',
  'Baking supply store',
  'Ballet school',
  'Balloon store',
  'Bank',
  'Bankruptcy attorney',
  'Banner store',
  'Banquet hall',
  'Baptist church',
  'Bar',
  'Bar & grill',
  'Barbecue restaurant',
  'Barber school',
  'Barber shop',
  'Bicycle club',
  'Bicycle rental service',
  'Bicycle repair shop',
  'Bicycle store',
  'Billiards supply store',
  'Bingo hall',
  'Blood bank',
  'Blood donation center',
  'BMW dealer',
  'Boat dealer',
  'Boat rental service',
  'Boat repair shop',
  'Body piercing shop',
  'Bookkeeping service',
  'Bookstore',
  'Botanical garden',
  'Bowling alley',
  'Boxing gym',
  'Bridal shop',
  'Building firm',
  'Bus company',
  'Business center',
  'Business development service',
  'Business management consultant',
  'Business park',
  'Butcher shop',
  'Cabinet maker',
  'Cafe',
  'Car dealer',
  'Car detailing service',
  'Car rental agency',
  'Car repair and maintenance service',
  'Car wash',
  'Carpenter',
  'Carpet cleaning service',
  'Carpet installer',
  'Carpet store',
  'Catering food and drink supplier',
  'CCTV installer',
  'Chauffeur service',
  'Chemical plant',
  'Child care agency',
  'Childminder',
  'Chinese restaurant',
  'Chiropractor',
  'Christmas store',
  'Church',
  'Cleaning products supplier',
  'Clothing store',
  'Coffee shop',
  'Commercial cleaning service',
  'Community centre',
  'Computer repair service',
  'Computer store',
  'Concert hall',
  'Construction company',
  'Consultant',
  'Convenience store',
  'Counsellor',
  'Courier service',
  'Coworking space',
  'Craft store',
  'Credit union',
  'Dance school',
  'Debt collection agency',
  'Decorator',
  'Dental clinic',
  'Department store',
  'Design agency',
  'Dog groomer',
  'Dog trainer',
  'Drainage service',
  'Driving instructor',
  'Driving school',
  'Drug store',
  'Dry cleaner',
  'Electrician',
  'Electronics repair shop',
  'Electronics store',
  'Embassy',
  'Employment agency',
  'Entertainment agency',
  'Environmental consultant',
  'Equipment rental agency',
  'Estate agent',
  'Event management company',
  'Event planner',
  'Event venue',
  'Exterminator',
  'Fabric store',
  'Fast food restaurant',
  'Financial consultant',
  'Financial planner',
  'Fire protection service',
  'Fitness centre',
  'Flooring store',
  'Florist',
  'Food bank',
  'Food manufacturer',
  'Funeral home',
  'Furniture maker',
  'Furniture store',
  'Garden centre',
  'Gas station',
  'General contractor',
  'Gift shop',
  'Glass merchant',
  'Golf club',
  'Graphic designer',
  'Grocery store',
  'Gym',
  'Hair salon',
  'Hardware store',
  'Health food store',
  'Home goods store',
  'Home inspector',
  'Home security company',
  'Hospital',
  'Hotel',
  'Indian restaurant',
  'Insurance agency',
  'Interior designer',
  'Italian restaurant',
  'Jeweller',
  'Joinery',
  'Kitchen remodeler',
  'Landscaper',
  'Language school',
  'Laundry service',
  'Law firm',
  'Legal services',
  'Leisure centre',
  'Library',
  'Life coach',
  'Locksmith',
  'Logo designer',
  'Marketing agency',
  'Martial arts school',
  'Massage therapist',
  'Mechanic',
  'Media company',
  'Medical clinic',
  'Mental health service',
  'Mexican restaurant',
  'Mobile caterer',
  'Mobile mechanic',
  'Mobile phone repair shop',
  'Mortgage broker',
  'Moving company',
  'Music school',
  'Nail salon',
  'Notary public',
  'Nursery school',
  'Nursing home',
  'Office supply store',
  'Oil change service',
  'Optician',
  'Orthodontist',
  'Osteopath',
  'Painter',
  'Park',
  'Parking lot',
  'Pest control service',
  'Pet groomer',
  'Pet shop',
  'Photographer',
  'Photography studio',
  'Physical therapist',
  'Pizza restaurant',
  'Plasterer',
  'Plumber',
  'Podiatrist',
  'Pool cleaning service',
  'Postal service',
  'Pottery class',
  'Pressure washing service',
  'Print shop',
  'Private investigator',
  'Property management company',
  'Psychiatrist',
  'Psychologist',
  'Pub',
  'Roofer',
  'Scaffolding contractor',
  'School',
  'Security company',
  'Skip hire service',
  'Solar energy company',
  'Solicitor',
  'Spa',
  'Sports club',
  'Sports complex',
  'Storage facility',
  'Supermarket',
  'Surveyor',
  'Takeaway restaurant',
  'Tattoo shop',
  'Tax preparation service',
  'Taxi service',
  'Theatre',
  'Tiler',
  'Towing service',
  'Travel agency',
  'Tree surgeon',
  'Tutoring service',
  'Tyre shop',
  'University',
  'Used car dealer',
  'Vet',
  'Video production service',
  'Vietnamese restaurant',
  'Warehouse',
  'Web designer',
  'Wedding photographer',
  'Wedding planner',
  'Wedding venue',
  'Window cleaner',
  'Window installation service',
  'Winery',
  'Yoga studio',
];
