export const UK_CITIES: string[] = [
  // England — London Boroughs & Areas
  "London",
  "Central London",
  "East London",
  "North London",
  "South London",
  "West London",
  "Barking",
  "Barnet",
  "Battersea",
  "Bexley",
  "Bow",
  "Brentford",
  "Brixton",
  "Bromley",
  "Camden",
  "Canary Wharf",
  "Chelsea",
  "Chiswick",
  "Clapham",
  "Croydon",
  "Dalston",
  "Ealing",
  "Enfield",
  "Finsbury Park",
  "Fulham",
  "Greenwich",
  "Hackney",
  "Hammersmith",
  "Haringey",
  "Harrow",
  "Havering",
  "Hillingdon",
  "Hounslow",
  "Islington",
  "Kensington",
  "Kingston upon Thames",
  "Lambeth",
  "Lewisham",
  "Merton",
  "Newham",
  "Peckham",
  "Putney",
  "Richmond",
  "Romford",
  "Southwark",
  "Stepney",
  "Streatham",
  "Sutton",
  "Tower Hamlets",
  "Tooting",
  "Tottenham",
  "Waltham Forest",
  "Wandsworth",
  "Westminster",
  "Wimbledon",
  "Woolwich",

  // England — South East
  "Brighton",
  "Hove",
  "Eastbourne",
  "Hastings",
  "Worthing",
  "Crawley",
  "Guildford",
  "Woking",
  "Reigate",
  "Maidstone",
  "Canterbury",
  "Dover",
  "Folkestone",
  "Chatham",
  "Gillingham",
  "Rochester",
  "Tunbridge Wells",
  "Tonbridge",
  "Ashford",
  "Margate",
  "Ramsgate",
  "Whitstable",
  "Sevenoaks",
  "Dartford",
  "Gravesend",
  "Sittingbourne",
  "Faversham",
  "Deal",
  "Chichester",
  "Horsham",
  "Bognor Regis",
  "Littlehampton",
  "Shoreham-by-Sea",
  "Lewes",
  "Uckfield",
  "Haywards Heath",
  "East Grinstead",
  "Burgess Hill",
  "Slough",
  "Windsor",
  "Maidenhead",
  "Bracknell",
  "Reading",
  "Wokingham",
  "Newbury",
  "Basingstoke",
  "Andover",
  "Winchester",
  "Eastleigh",
  "Fareham",
  "Gosport",
  "Portsmouth",
  "Southampton",
  "Havant",
  "Waterlooville",
  "Alton",
  "Fleet",
  "Farnborough",
  "Aldershot",
  "Farnham",
  "Oxford",
  "Abingdon",
  "Banbury",
  "Bicester",
  "Witney",
  "Didcot",
  "Henley-on-Thames",
  "Aylesbury",
  "High Wycombe",
  "Milton Keynes",
  "Bedford",
  "Luton",
  "Dunstable",
  "Stevenage",
  "Hemel Hempstead",
  "St Albans",
  "Watford",
  "Hertford",
  "Hitchin",
  "Letchworth",
  "Welwyn Garden City",
  "Hatfield",
  "Bishop's Stortford",
  "Harlow",
  "Chelmsford",
  "Colchester",
  "Ipswich",
  "Norwich",
  "Great Yarmouth",
  "Lowestoft",
  "Peterborough",
  "Ely",
  "Cambridge",
  "Huntingdon",
  "St Ives",
  "Wisbech",
  "King's Lynn",

  // England — South West
  "Bristol",
  "Bath",
  "Weston-super-Mare",
  "Taunton",
  "Yeovil",
  "Bridgwater",
  "Burnham-on-Sea",
  "Glastonbury",
  "Frome",
  "Minehead",
  "Salisbury",
  "Chippenham",
  "Swindon",
  "Trowbridge",
  "Devizes",
  "Marlborough",
  "Melksham",
  "Cirencester",
  "Cheltenham",
  "Gloucester",
  "Stroud",
  "Tewkesbury",
  "Hereford",
  "Ross-on-Wye",
  "Ledbury",
  "Exeter",
  "Plymouth",
  "Torquay",
  "Paignton",
  "Newton Abbot",
  "Barnstaple",
  "Ilfracombe",
  "Bideford",
  "Okehampton",
  "Ivybridge",
  "Totnes",
  "Dartmouth",
  "Truro",
  "Penzance",
  "Falmouth",
  "Newquay",
  "St Austell",
  "Bodmin",
  "Launceston",
  "Bournemouth",
  "Poole",
  "Weymouth",
  "Dorchester",
  "Bridport",
  "Sherborne",
  "Blandford Forum",

  // England — East Midlands
  "Nottingham",
  "Derby",
  "Leicester",
  "Lincoln",
  "Northampton",
  "Mansfield",
  "Chesterfield",
  "Loughborough",
  "Grantham",
  "Boston",
  "Skegness",
  "Grimsby",
  "Scunthorpe",
  "Kettering",
  "Corby",
  "Wellingborough",
  "Rushden",
  "Burton upon Trent",
  "Hinkley",
  "Melton Mowbray",
  "Market Harborough",
  "Long Eaton",
  "Ilkeston",
  "Matlock",
  "Buxton",
  "Newark-on-Trent",
  "Retford",
  "Worksop",

  // England — West Midlands
  "Birmingham",
  "Coventry",
  "Wolverhampton",
  "Stoke-on-Trent",
  "Walsall",
  "Dudley",
  "West Bromwich",
  "Solihull",
  "Sutton Coldfield",
  "Tamworth",
  "Lichfield",
  "Cannock",
  "Stafford",
  "Shrewsbury",
  "Telford",
  "Kidderminster",
  "Worcester",
  "Redditch",
  "Bromsgrove",
  "Leamington Spa",
  "Nuneaton",
  "Rugby",
  "Warwick",
  "Stratford-upon-Avon",
  "Hereford",
  "Leominster",
  "Bridgnorth",

  // England — North West
  "Manchester",
  "Liverpool",
  "Preston",
  "Bolton",
  "Blackpool",
  "Burnley",
  "Blackburn",
  "Wigan",
  "Salford",
  "Oldham",
  "Rochdale",
  "Stockport",
  "Bury",
  "Warrington",
  "Chester",
  "Crewe",
  "Macclesfield",
  "Carlisle",
  "Barrow-in-Furness",
  "Lancaster",
  "Morecambe",
  "Kendal",
  "Accrington",
  "Nelson",
  "Colne",
  "Chorley",
  "Southport",
  "St Helens",
  "Birkenhead",
  "Wallasey",
  "Ellesmere Port",
  "Runcorn",
  "Widnes",
  "Fleetwood",
  "Lytham St Annes",
  "Clitheroe",
  "Rawtenstall",

  // England — Yorkshire & Humber
  "Leeds",
  "Sheffield",
  "Bradford",
  "Hull",
  "York",
  "Huddersfield",
  "Halifax",
  "Barnsley",
  "Rotherham",
  "Doncaster",
  "Wakefield",
  "Harrogate",
  "Scarborough",
  "Middlesbrough",
  "Sunderland",
  "Castleford",
  "Pontefract",
  "Dewsbury",
  "Batley",
  "Keighley",
  "Bingley",
  "Shipley",
  "Skipton",
  "Selby",
  "Beverley",
  "Bridlington",
  "Filey",
  "Whitby",
  "Ripon",
  "Thirsk",
  "Malton",
  "Grimsby",
  "Cleethorpes",
  "Immingham",
  "Scunthorpe",

  // England — North East
  "Newcastle upon Tyne",
  "Gateshead",
  "Sunderland",
  "Durham",
  "Darlington",
  "Hartlepool",
  "Stockton-on-Tees",
  "Middlesbrough",
  "Redcar",
  "South Shields",
  "North Shields",
  "Whitley Bay",
  "Hexham",
  "Berwick-upon-Tweed",
  "Peterlee",
  "Newton Aycliffe",
  "Consett",
  "Chester-le-Street",
  "Washington",
  "Cramlington",
  "Blyth",
  "Ashington",
  "Morpeth",
  "Alnwick",
  "Seaham",

  // England — East of England
  "Ipswich",
  "Norwich",
  "Colchester",
  "Chelmsford",
  "Southend-on-Sea",
  "Basildon",
  "Harlow",
  "Brentwood",
  "Braintree",
  "Clacton-on-Sea",
  "Bury St Edmunds",
  "Lowestoft",
  "Great Yarmouth",
  "Thetford",
  "Newmarket",
  "Haverhill",
  "Sudbury",
  "Wymondham",

  // Scotland
  "Edinburgh",
  "Glasgow",
  "Aberdeen",
  "Dundee",
  "Inverness",
  "Perth",
  "Stirling",
  "Livingston",
  "Paisley",
  "East Kilbride",
  "Motherwell",
  "Hamilton",
  "Ayr",
  "Cumbernauld",
  "Falkirk",
  "Kirkcaldy",
  "Dunfermline",
  "Glenrothes",
  "St Andrews",
  "Dumfries",
  "Kilmarnock",
  "Greenock",
  "Coatbridge",
  "Airdrie",
  "Grangemouth",
  "Fort William",
  "Oban",
  "Elgin",
  "Fraserburgh",
  "Peterhead",
  "Galashiels",
  "Hawick",
  "Bathgate",
  "Wishaw",
  "Loch Lomond",

  // Wales
  "Cardiff",
  "Swansea",
  "Newport",
  "Wrexham",
  "Merthyr Tydfil",
  "Bridgend",
  "Barry",
  "Caerphilly",
  "Neath",
  "Port Talbot",
  "Rhondda",
  "Llanelli",
  "Carmarthen",
  "Aberystwyth",
  "Bangor",
  "Colwyn Bay",
  "Rhyl",
  "Prestatyn",
  "Flint",
  "Mold",
  "Abergavenny",
  "Caernarfon",
  "Llangollen",
  "Pontypridd",
  "Penarth",
  "Aberdare",
  "Ebbw Vale",
  "Monmouth",
  "Haverfordwest",
  "Pembroke",
  "Fishguard",

  // Northern Ireland
  "Belfast",
  "Derry",
  "Londonderry",
  "Lisburn",
  "Newtownabbey",
  "Bangor",
  "Craigavon",
  "Ballymena",
  "Newry",
  "Antrim",
  "Carrickfergus",
  "Omagh",
  "Coleraine",
  "Enniskillen",
  "Larne",
  "Magherafelt",
  "Strabane",
  "Dungannon",
  "Downpatrick",
  "Armagh",
  "Newtonards",
  "Ballymoney",
  "Portrush",
].sort((a, b) => a.localeCompare(b));
