// UK postcode districts grouped by postcode area, for the Admin "Postcode sweep"
// tool. Search "[trade] [district]" (e.g. "electrician B1") one at a time to get
// fresh results per district and cover the whole country systematically.

export type PostcodeArea = { area: string; name: string; districts: string[] };

// Helper: expand a numeric range like r("AB", 10, 16) → ["AB10",…,"AB16"].
const r = (p: string, a: number, b: number): string[] => {
  const out: string[] = [];
  for (let i = a; i <= b; i++) out.push(p + i);
  return out;
};

export const UK_POSTCODES: PostcodeArea[] = [
  { area: "AB", name: "Aberdeen", districts: [...r("AB", 10, 16), ...r("AB", 21, 25), ...r("AB", 30, 39), ...r("AB", 41, 45), ...r("AB", 51, 56), "AB99"] },
  { area: "AL", name: "St Albans", districts: r("AL", 1, 10) },
  { area: "B", name: "Birmingham", districts: [...r("B", 1, 21), ...r("B", 23, 38), "B40", ...r("B", 42, 50), ...r("B", 60, 80), ...r("B", 90, 99)] },
  { area: "BA", name: "Bath", districts: [...r("BA", 1, 16), ...r("BA", 20, 22)] },
  { area: "BB", name: "Blackburn", districts: [...r("BB", 1, 12), "BB18"] },
  { area: "BD", name: "Bradford", districts: [...r("BD", 1, 24), ...r("BD", 97, 99)] },
  { area: "BH", name: "Bournemouth", districts: [...r("BH", 1, 25), "BH31"] },
  { area: "BL", name: "Bolton", districts: [...r("BL", 0, 9), "BL11", "BL78"] },
  { area: "BN", name: "Brighton", districts: [...r("BN", 1, 3), ...r("BN", 5, 18), ...r("BN", 20, 27), ...r("BN", 41, 45), ...r("BN", 50, 52), "BN88", "BN95", "BN99"] },
  { area: "BR", name: "Bromley", districts: r("BR", 1, 8) },
  { area: "BS", name: "Bristol", districts: [...r("BS", 1, 11), ...r("BS", 13, 16), ...r("BS", 20, 32), ...r("BS", 34, 37), "BS39", "BS40", "BS41", ...r("BS", 48, 49), "BS98", "BS99"] },
  { area: "BT", name: "Belfast", districts: [...r("BT", 1, 49), ...r("BT", 51, 57), ...r("BT", 60, 71), ...r("BT", 74, 82), ...r("BT", 92, 94)] },
  { area: "CA", name: "Carlisle", districts: [...r("CA", 1, 28), "CA95"] },
  { area: "CB", name: "Cambridge", districts: [...r("CB", 1, 11), ...r("CB", 21, 25)] },
  { area: "CF", name: "Cardiff", districts: ["CF3", "CF5", "CF10", "CF11", "CF14", "CF15", "CF23", "CF24", ...r("CF", 30, 48), ...r("CF", 61, 64), "CF71", "CF72", "CF81", "CF82", "CF83", "CF91", "CF95", "CF99"] },
  { area: "CH", name: "Chester", districts: [...r("CH", 1, 8), ...r("CH", 25, 34), ...r("CH", 41, 49), ...r("CH", 60, 66), "CH70", "CH88", "CH99"] },
  { area: "CM", name: "Chelmsford", districts: [...r("CM", 0, 9), ...r("CM", 11, 24), "CM77", "CM92", "CM98", "CM99"] },
  { area: "CO", name: "Colchester", districts: r("CO", 1, 16) },
  { area: "CR", name: "Croydon", districts: ["CR0", ...r("CR", 2, 9), "CR90"] },
  { area: "CT", name: "Canterbury", districts: [...r("CT", 1, 21), "CT50"] },
  { area: "CV", name: "Coventry", districts: [...r("CV", 1, 13), ...r("CV", 21, 23), ...r("CV", 31, 37), "CV47"] },
  { area: "CW", name: "Crewe", districts: [...r("CW", 1, 12), "CW98"] },
  { area: "DA", name: "Dartford", districts: r("DA", 1, 18) },
  { area: "DD", name: "Dundee", districts: r("DD", 1, 11) },
  { area: "DE", name: "Derby", districts: ["DE1", ...r("DE", 3, 7), ...r("DE", 11, 15), ...r("DE", 21, 24), "DE45", "DE55", "DE56", "DE65", "DE72", "DE73", "DE74", "DE75", "DE99"] },
  { area: "DG", name: "Dumfries", districts: [...r("DG", 1, 14), "DG16"] },
  { area: "DH", name: "Durham", districts: [...r("DH", 1, 9), "DH97", "DH98", "DH99"] },
  { area: "DL", name: "Darlington", districts: [...r("DL", 1, 17), "DL98"] },
  { area: "DN", name: "Doncaster", districts: [...r("DN", 1, 12), ...r("DN", 14, 22), ...r("DN", 31, 41)] },
  { area: "DT", name: "Dorchester", districts: r("DT", 1, 11) },
  { area: "DY", name: "Dudley", districts: r("DY", 1, 14) },
  { area: "E", name: "East London", districts: [...r("E", 1, 18), "E1W", "E20", "E22", "E98"] },
  { area: "EC", name: "East Central London", districts: ["EC1A", "EC1M", "EC1N", "EC1P", "EC1R", "EC1V", "EC1Y", "EC2A", "EC2M", "EC2N", "EC2P", "EC2R", "EC2V", "EC2Y", "EC3A", "EC3M", "EC3N", "EC3P", "EC3R", "EC3V", "EC4A", "EC4M", "EC4N", "EC4P", "EC4R", "EC4V", "EC4Y"] },
  { area: "EH", name: "Edinburgh", districts: [...r("EH", 1, 55), "EH91", "EH95", "EH99"] },
  { area: "EN", name: "Enfield", districts: r("EN", 1, 11) },
  { area: "EX", name: "Exeter", districts: [...r("EX", 1, 24), ...r("EX", 31, 39)] },
  { area: "FK", name: "Falkirk", districts: r("FK", 1, 21) },
  { area: "FY", name: "Blackpool", districts: r("FY", 1, 8) },
  { area: "G", name: "Glasgow", districts: [...r("G", 1, 5), ...r("G", 11, 15), ...r("G", 20, 23), ...r("G", 31, 34), ...r("G", 40, 46), ...r("G", 51, 53), "G58", ...r("G", 60, 79), ...r("G", 81, 84), "G90"] },
  { area: "GL", name: "Gloucester", districts: [...r("GL", 1, 20), ...r("GL", 50, 56)] },
  { area: "GU", name: "Guildford", districts: [...r("GU", 1, 12), ...r("GU", 14, 35), "GU46", "GU47", "GU51", "GU52"] },
  { area: "HA", name: "Harrow", districts: r("HA", 0, 9) },
  { area: "HD", name: "Huddersfield", districts: r("HD", 1, 9) },
  { area: "HG", name: "Harrogate", districts: r("HG", 1, 5) },
  { area: "HP", name: "Hemel Hempstead", districts: [...r("HP", 1, 23), "HP27"] },
  { area: "HR", name: "Hereford", districts: r("HR", 1, 9) },
  { area: "HS", name: "Hebrides", districts: r("HS", 1, 9) },
  { area: "HU", name: "Hull", districts: r("HU", 1, 20) },
  { area: "HX", name: "Halifax", districts: r("HX", 1, 7) },
  { area: "IG", name: "Ilford", districts: r("IG", 1, 11) },
  { area: "IP", name: "Ipswich", districts: [...r("IP", 1, 33), "IP98"] },
  { area: "IV", name: "Inverness", districts: [...r("IV", 1, 28), "IV30", "IV31", "IV32", "IV36", ...r("IV", 40, 49), ...r("IV", 51, 56), "IV63", "IV99"] },
  { area: "KA", name: "Kilmarnock", districts: r("KA", 1, 30) },
  { area: "KT", name: "Kingston upon Thames", districts: r("KT", 1, 24) },
  { area: "KW", name: "Kirkwall", districts: ["KW1", "KW2", "KW3", ...r("KW", 5, 17)] },
  { area: "KY", name: "Kirkcaldy", districts: [...r("KY", 1, 16), "KY99"] },
  { area: "L", name: "Liverpool", districts: [...r("L", 1, 40), ...r("L", 67, 72), "L74", "L75"] },
  { area: "LA", name: "Lancaster", districts: r("LA", 1, 23) },
  { area: "LD", name: "Llandrindod Wells", districts: r("LD", 1, 8) },
  { area: "LE", name: "Leicester", districts: [...r("LE", 1, 19), "LE21", "LE41", "LE65", "LE67", "LE87", "LE94", "LE95"] },
  { area: "LL", name: "Llandudno", districts: r("LL", 11, 78) },
  { area: "LN", name: "Lincoln", districts: r("LN", 1, 13) },
  { area: "LS", name: "Leeds", districts: [...r("LS", 1, 29), "LS88", "LS98", "LS99"] },
  { area: "LU", name: "Luton", districts: r("LU", 1, 7) },
  { area: "M", name: "Manchester", districts: [...r("M", 1, 9), ...r("M", 11, 35), "M38", "M40", "M41", ...r("M", 43, 46), "M50", "M60", "M61", "M90", "M99"] },
  { area: "ME", name: "Rochester", districts: r("ME", 1, 20) },
  { area: "MK", name: "Milton Keynes", districts: [...r("MK", 1, 20), ...r("MK", 40, 46), "MK77"] },
  { area: "ML", name: "Motherwell", districts: r("ML", 1, 12) },
  { area: "N", name: "North London", districts: [...r("N", 1, 22), "N1C", "N1P", "N81"] },
  { area: "NE", name: "Newcastle upon Tyne", districts: [...r("NE", 1, 13), ...r("NE", 15, 49), ...r("NE", 61, 71), "NE85", "NE88", "NE92", "NE98", "NE99"] },
  { area: "NG", name: "Nottingham", districts: [...r("NG", 1, 25), ...r("NG", 31, 34), "NG80", "NG90"] },
  { area: "NN", name: "Northampton", districts: [...r("NN", 1, 18), "NN29"] },
  { area: "NP", name: "Newport", districts: ["NP4", "NP7", "NP8", ...r("NP", 10, 13), "NP15", "NP16", ...r("NP", 18, 20), ...r("NP", 22, 26), "NP44"] },
  { area: "NR", name: "Norwich", districts: [...r("NR", 1, 35), "NR99"] },
  { area: "NW", name: "North West London", districts: [...r("NW", 1, 11), "NW1W", "NW26"] },
  { area: "OL", name: "Oldham", districts: r("OL", 1, 16) },
  { area: "OX", name: "Oxford", districts: [...r("OX", 1, 5), "OX7", "OX9", ...r("OX", 10, 18), "OX20", ...r("OX", 25, 29), "OX33", "OX39", "OX44", "OX49"] },
  { area: "PA", name: "Paisley", districts: [...r("PA", 1, 49), ...r("PA", 60, 80)] },
  { area: "PE", name: "Peterborough", districts: r("PE", 1, 38) },
  { area: "PH", name: "Perth", districts: [...r("PH", 1, 26), ...r("PH", 30, 44), "PH49", "PH50"] },
  { area: "PL", name: "Plymouth", districts: [...r("PL", 1, 35), "PL95"] },
  { area: "PO", name: "Portsmouth", districts: r("PO", 1, 41) },
  { area: "PR", name: "Preston", districts: [...r("PR", 0, 11), "PR25", "PR26"] },
  { area: "RG", name: "Reading", districts: ["RG1", "RG2", ...r("RG", 4, 10), "RG12", "RG14", "RG17", "RG18", "RG19", ...r("RG", 20, 31), ...r("RG", 40, 42), "RG45"] },
  { area: "RH", name: "Redhill", districts: [...r("RH", 1, 20), "RH77"] },
  { area: "RM", name: "Romford", districts: r("RM", 1, 20) },
  { area: "S", name: "Sheffield", districts: [...r("S", 1, 14), "S17", "S18", "S20", "S21", "S25", "S26", "S32", "S33", "S35", "S36", ...r("S", 40, 45), "S49", ...r("S", 60, 66), ...r("S", 70, 75), "S80", "S81", ...r("S", 95, 99)] },
  { area: "SA", name: "Swansea", districts: [...r("SA", 1, 20), ...r("SA", 31, 48), ...r("SA", 61, 73), "SA80", "SA99"] },
  { area: "SE", name: "South East London", districts: [...r("SE", 1, 28), "SE1P"] },
  { area: "SG", name: "Stevenage", districts: r("SG", 1, 19) },
  { area: "SK", name: "Stockport", districts: [...r("SK", 1, 17), "SK22", "SK23"] },
  { area: "SL", name: "Slough", districts: [...r("SL", 0, 9), "SL60", "SL95"] },
  { area: "SM", name: "Sutton", districts: r("SM", 1, 7) },
  { area: "SN", name: "Swindon", districts: [...r("SN", 1, 16), "SN25", "SN26", "SN38", "SN99"] },
  { area: "SO", name: "Southampton", districts: [...r("SO", 14, 25), ...r("SO", 30, 32), ...r("SO", 40, 43), "SO45", ...r("SO", 50, 53), "SO97"] },
  { area: "SP", name: "Salisbury", districts: r("SP", 1, 11) },
  { area: "SR", name: "Sunderland", districts: r("SR", 1, 8) },
  { area: "SS", name: "Southend-on-Sea", districts: [...r("SS", 0, 9), ...r("SS", 11, 17), "SS22", "SS99"] },
  { area: "ST", name: "Stoke-on-Trent", districts: [...r("ST", 1, 21), "ST55"] },
  { area: "SW", name: "South West London", districts: [...r("SW", 2, 20), "SW1A", "SW1E", "SW1H", "SW1P", "SW1V", "SW1W", "SW1X", "SW1Y", "SW95"] },
  { area: "SY", name: "Shrewsbury", districts: [...r("SY", 1, 25), "SY99"] },
  { area: "TA", name: "Taunton", districts: r("TA", 1, 24) },
  { area: "TD", name: "Galashiels", districts: r("TD", 1, 15) },
  { area: "TF", name: "Telford", districts: r("TF", 1, 13) },
  { area: "TN", name: "Tunbridge Wells", districts: r("TN", 1, 40) },
  { area: "TQ", name: "Torquay", districts: r("TQ", 1, 14) },
  { area: "TR", name: "Truro", districts: r("TR", 1, 27) },
  { area: "TS", name: "Cleveland", districts: r("TS", 1, 29) },
  { area: "TW", name: "Twickenham", districts: r("TW", 1, 20) },
  { area: "UB", name: "Southall", districts: [...r("UB", 1, 11), "UB18"] },
  { area: "W", name: "West London", districts: [...r("W", 2, 14), "W1A", "W1B", "W1C", "W1D", "W1F", "W1G", "W1H", "W1J", "W1K", "W1S", "W1T", "W1U", "W1W"] },
  { area: "WA", name: "Warrington", districts: [...r("WA", 1, 16), "WA55", "WA88"] },
  { area: "WC", name: "West Central London", districts: ["WC1A", "WC1B", "WC1E", "WC1H", "WC1N", "WC1R", "WC1V", "WC1X", "WC2A", "WC2B", "WC2E", "WC2H", "WC2N", "WC2R"] },
  { area: "WD", name: "Watford", districts: ["WD3", "WD4", "WD5", "WD6", "WD7", "WD17", "WD18", "WD19", "WD23", "WD24", "WD25", "WD99"] },
  { area: "WF", name: "Wakefield", districts: [...r("WF", 1, 17), "WF90"] },
  { area: "WN", name: "Wigan", districts: r("WN", 1, 8) },
  { area: "WR", name: "Worcester", districts: [...r("WR", 1, 15), "WR99"] },
  { area: "WS", name: "Walsall", districts: r("WS", 1, 15) },
  { area: "WV", name: "Wolverhampton", districts: [...r("WV", 1, 16), "WV98", "WV99"] },
  { area: "YO", name: "York", districts: ["YO1", "YO7", "YO8", ...r("YO", 10, 19), ...r("YO", 21, 26), "YO30", "YO31", "YO32", "YO41", "YO42", "YO43", "YO51", "YO60", "YO61", "YO62", "YO90"] },
  { area: "ZE", name: "Lerwick", districts: ["ZE1", "ZE2", "ZE3"] },
];
